[build]
  command = """
    git clone https://github.com/flutter/flutter.git -b stable
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter config --no-analytics
    flutter doctor
    flutter pub get
    flutter build web --release
  """
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "stable"